name: Build and publish test coverage
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [10, 12]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Test
        run: test:unit-coverage
      
      - name: Publish test coverage report
        uses: EndBug/add-and-commit@v4
        with:
          add: docs
          force: true
          message: Add generated docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}